// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/19/2024, 11:11:33 PM
const configMerger = require("/Users/alfarouq/Desktop/online-store-nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/alfarouq/Desktop/online-store-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfarouq/Desktop/online-store-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfarouq/Desktop/online-store-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfarouq/Desktop/online-store-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfarouq/Desktop/online-store-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alfarouq/Desktop/online-store-nuxt/plugins/**/*.{js,ts,mjs}","/Users/alfarouq/Desktop/online-store-nuxt/composables/**/*.{js,ts,mjs}","/Users/alfarouq/Desktop/online-store-nuxt/utils/**/*.{js,ts,mjs}","/Users/alfarouq/Desktop/online-store-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/alfarouq/Desktop/online-store-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/alfarouq/Desktop/online-store-nuxt/app.config.{js,ts,mjs}"] } }));

module.exports = config
